version: '3'
services:
  siren:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:80
    restart: always

  transfer_api:
    build:
      context: .
      dockerfile: ./Dockerfile.transferQuery
    ports:
      - 8080:8080
    restart: always
