name: debug

on:
  workflow_dispatch:
  push:
    branches:
      - debug-gpg

run-name: debug gpg stuff
jobs:
  debug:
    runs-on: ubuntu-22.04
    steps:
      - name: Configure GPG
        env:
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          export GPG_TTY=$(tty)
          echo "$GPG_SIGNING_KEY" | gpg --batch --import
      - name: check identities
        run: |
          gpg --list-signatures
